# Generated by Django 4.0 on 2021-12-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ACADEMICO', 'Académico'), ('LEGAL', 'Legal'), ('ADMINISTRATIVO', 'Administrativo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TramiteUniv',
            fields=[
                ('id_tramite_univ', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=100)),
                ('is_salud', models.BooleanField(default=False)),
                ('nivel', models.CharField(choices=[('E', 'Especialidad'), ('M', 'Maestría'), ('L', 'Licenciatura'), ('D', 'Doctorado')], max_length=20, null=True)),
                ('modalidad', models.CharField(choices=[('E', 'Escolarizada'), ('M', 'Mixta'), ('NE-D', 'No Escolarizada - D'), ('NE-L', 'No Escolarizada - L')], max_length=20, null=True)),
                ('ciclo', models.CharField(choices=[('TRIM', 'Trimestral'), ('CUATRIM', 'Cuatrimestral'), ('SEM', 'Semestral'), ('MODULAR', '5 semanas')], max_length=20, null=True)),
                ('objetivo', models.CharField(choices=[('NUEVA', 'Nueva'), ('ACTUALIZACION', 'Actualización'), ('ACT/MOD-IMPORT', 'Actualización / Modificación por importación'), ('ACT-CAMBIO-MOD', 'Actualización por cambio de modalidad'), ('EXTENSION', 'Extensión')], max_length=20, null=True)),
                ('programa_madre', models.CharField(max_length=20, null=True)),
                ('fecha_recep_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_com_acad', models.DateField(blank=True, null=True)),
                ('fecha_com_dir', models.DateField(blank=True, null=True)),
                ('fecha_paquetes_rl', models.DateField(blank=True, null=True)),
                ('fecha_acuerdo_sep', models.DateField(blank=True, null=True)),
                ('fecha_limite_apertura', models.DateField(blank=True, null=True)),
                ('status_tramite', models.CharField(max_length=200, null=True)),
                ('notas_entrega_paqs', models.CharField(max_length=500, null=True)),
                ('checklist_tramite', models.ManyToManyField(through='univ.Checklist', to='univ.Documento')),
            ],
        ),
    ]
