# Generated by Django 4.0 on 2021-12-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('univ', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramiteuniv',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='id_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='univ.documento'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='id_tramite_univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='univ.tramiteuniv'),
        ),
    ]
