# Generated by Django 4.0 on 2021-12-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramiteuniv',
            name='solicitante',
            field=models.CharField(choices=[('UT', 'Universidad de Tamaulipas'), ('UQ', 'Universidad de Querétaro'), ('UV', 'Universidad de Veracruz'), ('UM', 'Universidad de Monterrey')], max_length=50, null=True),
        ),
    ]
