# Generated by Django 4.0 on 2021-12-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0003_tramiteuniv_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramiteuniv',
            name='checklist_tramite',
            field=models.ManyToManyField(null=True, through='univ.Checklist', to='univ.Documento'),
        ),
    ]
