# Generated by Django 4.0 on 2021-12-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0004_alter_tramiteuniv_checklist_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramiteuniv',
            name='checklist_tramite',
            field=models.ManyToManyField(through='univ.Checklist', to='univ.Documento'),
        ),
    ]
