# Generated by Django 4.0 on 2021-12-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('univ', '0003_tramiteuniv_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteSep',
            fields=[
                ('id_tramitesep', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('numero_op', models.IntegerField()),
                ('llavePago', models.CharField(max_length=50)),
                ('secuencia', models.CharField(blank=True, max_length=50)),
                ('objetivoSep', models.CharField(max_length=50)),
                ('no_tramiteSisrvoe', models.IntegerField(null=True)),
                ('observaciones_sisrvoe', models.CharField(max_length=200, null=True)),
                ('fecha_sisrvoe', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('id_tramiteuniv', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='univ.tramiteuniv')),
            ],
        ),
    ]
