# Generated by Django 4.0 on 2021-12-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramitesep',
            old_name='llavePago',
            new_name='llave_pago',
        ),
        migrations.RenameField(
            model_name='tramitesep',
            old_name='no_tramiteSisrvoe',
            new_name='no_tramite_sisrvoe',
        ),
        migrations.RenameField(
            model_name='tramitesep',
            old_name='objetivoSep',
            new_name='objetivo_sep',
        ),
        migrations.RenameField(
            model_name='tramitesep',
            old_name='tipoPago',
            new_name='tipo_pago',
        ),
        migrations.AddField(
            model_name='tramitesep',
            name='fecha_limite_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitesep',
            name='fecha_resp_enviadaSisrvoe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitesep',
            name='fecha_rvoe_obtenido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitesep',
            name='observaciones',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='respuestaSisrvoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateField()),
                ('observaciones', models.CharField(max_length=254, null=True)),
                ('id_tramitesep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sep.tramitesep')),
            ],
        ),
    ]
